# The latest powershell gives us more flexiablity to use Windows DSC items
- name: Windows | Install Powershell 5.0
  hosts: windows
  tasks:
   - win_chocolatey:
       name: "powershell"
     register: check_powershell5
     become: yes
     become_user: Administrator
     become_method: runas
     retries: 3
     delay: 10
